# Change these first
owner: emryl # Your GitHub organization or username, where this repository lives
repo: upptime-sl # The name of this repository

sites:
  - name: SL
    url: https://sl.se
  - name: SL Mina sidor
    url: https://mitt.sl.se
    icon: https://icons.duckduckgo.com/ip3/sl.se.ico
  - name: foretagare.sl.se
    url: https://foretagare.sl.se/foretag/
    icon: https://icons.duckduckgo.com/ip3/sl.se.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime-sl
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
# Configured Slack #upptime @emryl

# https://sl.se/?mode=travelPlanner&origName=S%C3%B6rskogen+%28Huddinge%29&origSiteId=7020&origPlaceId=QT0xQE89U8O2cnNrb2dlbiAoSHVkZGluZ2UpQFg9MTc5ODk5NTlAWT01OTIyMjI2NUBVPTc0QEw9MzAwMTA3MDIwQEI9MUBwPTE2NzY3NzU2MjFA&destName=SL+Huvudkontor%2C+Lindhagensgatan+100&destPlaceId=QT00QE89U0wgSHV2dWRrb250b3IsIExpbmRoYWdlbnNnYXRhbiAxMDBAWD0xODAxMzgwN0BZPTU5MzM1MTA3QFU9MTc1QEw9OTgwMDAwMDA0QEI9MUBwPTE2NzY2ODkzMTJA&transportTypes=111&enableOccupancyInformation=true
# https://webcloud.sl.se/v2/api/travels?desiredResults=3&destPlaceId=QT0xQE89TGluZGhhZ2Vuc2dhdGFuIChTdG9ja2hvbG0pQFg9MTgwMTU3NDlAWT01OTMzMzkyMEBVPTc0QEw9MzAwMTAxMjY5QEI9MUBwPTE2NzY4NjIwMjFA&enableOccupancyInformation=false&mode=travelPlanner&origPlaceId=QT0xQE89U8O2cnNrb2dlbiAoSHVkZGluZ2UpQFg9MTc5ODk5NTlAWT01OTIyMjI2NUBVPTc0QEw9MzAwMTA3MDIwQEI9MUBwPTE2NzY4NjIwMjFA&origSiteId=7020&searchForArrival=false&transportTypes=111&destName=Lindhagensgatan+%28Stockholm%29&origName=S%C3%B6rskogen+%28Huddinge%29&useCache=false
# https://services.c.web.sl.se/h4/api/travels?desiredResults=3&destPlaceId=QT00QE89U0wgSHV2dWRrb250b3IsIExpbmRoYWdlbnNnYXRhbiAxMDBAWD0xODAxMzgwN0BZPTU5MzM1MTA3QFU9MTc1QEw9OTgwMDAwMDA0QEI9MUBwPTE2NzY2ODkzMTJA&enableOccupancyInformation=true&mode=travelPlanner&origPlaceId=QT0xQE89U8O2cnNrb2dlbiAoSHVkZGluZ2UpQFg9MTc5ODk5NTlAWT01OTIyMjI2NUBVPTc0QEw9MzAwMTA3MDIwQEI9MUBwPTE2NzY3NzU2MjFA&searchForArrival=false&transportTypes=111
